import PDFDocument from "pdfkit";

/**
 * Turns a structured outline into PDF bytes with pdfkit.
 *
 * Kept apart from the agent so the layout is testable on its own: call
 * `renderPdf` with a hand-written outline and you get a file, no model needed.
 *
 * pdfkit is a streaming API with no "give me a Buffer" call, so the chunks are
 * collected by hand and joined once the document ends.
 */

export type PdfSection = { heading: string; paragraphs: string[]; bullets?: string[] };

export type PdfDocumentSpec = {
  title: string;
  subtitle?: string;
  sections: PdfSection[];
};

const COLORS = {
  title: "#0F172A",
  heading: "#2563EB",
  body: "#334155",
  muted: "#94A3B8",
  rule: "#E2E8F0",
};

export async function renderPdf(spec: PdfDocumentSpec): Promise<Buffer> {
  const doc = new PDFDocument({
    size: "A4",
    margin: 56,
    bufferPages: true,
    info: {
      Title: spec.title,
      Author: "AI Secretary",
      Creator: "AI Secretary PDF Agent",
    },
  });

  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const done = new Promise<void>((resolve, reject) => {
    doc.on("end", () => resolve());
    doc.on("error", reject);
  });

  // ── Cover ───────────────────────────────────────────────────────────────
  doc.moveDown(6);
  doc.fontSize(28).fillColor(COLORS.title).text(spec.title, { align: "center" });

  if (spec.subtitle) {
    doc.moveDown(0.6);
    doc
      .fontSize(13)
      .fillColor(COLORS.muted)
      .text(spec.subtitle, { align: "center" });
  }

  doc.moveDown(1.2);
  doc
    .fontSize(9)
    .fillColor(COLORS.muted)
    .text(
      `Generated by AI Secretary on ${new Date().toLocaleDateString(undefined, {
        day: "numeric",
        month: "long",
        year: "numeric",
      })}`,
      { align: "center" },
    );

  // ── Body ────────────────────────────────────────────────────────────────
  for (const section of spec.sections) {
    doc.addPage();

    doc.fontSize(18).fillColor(COLORS.heading).text(section.heading);
    doc.moveDown(0.4);

    // Horizontal rule under the heading.
    const ruleY = doc.y;
    doc
      .moveTo(doc.page.margins.left, ruleY)
      .lineTo(doc.page.width - doc.page.margins.right, ruleY)
      .strokeColor(COLORS.rule)
      .lineWidth(1)
      .stroke();

    doc.moveDown(0.8);

    for (const paragraph of section.paragraphs) {
      doc
        .fontSize(11)
        .fillColor(COLORS.body)
        .text(paragraph, { align: "left", lineGap: 4 });
      doc.moveDown(0.6);
    }

    for (const bullet of section.bullets ?? []) {
      doc
        .fontSize(11)
        .fillColor(COLORS.body)
        .text(`•  ${bullet}`, {
          // Hanging indent so wrapped lines align under the text, not the dot.
          indent: 12,
          align: "left",
          lineGap: 3,
        });
      doc.moveDown(0.3);
    }
  }

  // ── Page numbers ────────────────────────────────────────────────────────
  // bufferPages: true is what makes it possible to go back and stamp these
  // once the total is known.
  const range = doc.bufferedPageRange();

  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(range.start + index);
    doc
      .fontSize(8)
      .fillColor(COLORS.muted)
      .text(
        `${index + 1} / ${range.count}`,
        doc.page.margins.left,
        doc.page.height - 40,
        { align: "center", width: doc.page.width - 112 },
      );
  }

  doc.end();
  await done;

  return Buffer.concat(chunks);
}
