import pptxgenjs from "pptxgenjs";

/**
 * Turns a structured deck outline into .pptx bytes with pptxgenjs.
 *
 * Four slide layouts, each a function, so adding a fifth is a local change:
 *   cover      - dark title slide
 *   bullets    - white slide, each point in its own soft card
 *   stats      - dark slide, big numbers in columns
 *   conclusion - accent-coloured takeaways
 *
 * All positions are in inches on a 13.33 x 7.5 widescreen canvas.
 */

/**
 * pptxgenjs ships `export as namespace PptxGenJS` next to
 * `export default PptxGenJS`, which makes TypeScript resolve the default
 * export to the module object rather than to the class. The runtime value is
 * the constructor, so it is cast once here and the rest of the file works
 * against the two structural types below.
 */
type SlideOptions = Record<string, unknown>;

type Slide = {
  background: { color: string };
  addText(text: string, options: SlideOptions): unknown;
  addShape(shapeType: string, options: SlideOptions): unknown;
};

type Presentation = {
  layout: string;
  author: string;
  title: string;
  subject: string;
  ShapeType: Record<string, string>;
  addSlide(): Slide;
  write(options: { outputType: string }): Promise<unknown>;
};

const Pptx = pptxgenjs as unknown as new () => Presentation;

const THEME = {
  dark: "0F172A",
  primary: "2563EB",
  primaryDeep: "1D4ED8",
  white: "FFFFFF",
  offWhite: "F8FAFC",
  card: "EFF6FF",
  cardLine: "DBEAFE",
  text: "1E293B",
  muted: "64748B",
  dim: "94A3B8",
  pale: "CBD5E1",
  panel: "1E3A5F",
};

const FONT = "Calibri";

export type DeckSlide =
  | { type: "bullets"; title: string; items: string[] }
  | { type: "stats"; title: string; stats: Array<{ label: string; value: string }> }
  | { type: "conclusion"; title: string; items: string[] };

export type DeckSpec = {
  title: string;
  subtitle?: string;
  slides: DeckSlide[];
};

function addCover(ppt: Presentation, title: string, subtitle?: string) {
  const slide = ppt.addSlide();
  slide.background = { color: THEME.dark };

  // Two translucent circles, bleeding off opposite corners.
  slide.addShape(ppt.ShapeType.ellipse, {
    x: 10.5,
    y: -1.2,
    w: 4,
    h: 4,
    fill: { color: THEME.primary, transparency: 75 },
    line: { color: THEME.primary, transparency: 75 },
  });

  slide.addShape(ppt.ShapeType.ellipse, {
    x: -0.8,
    y: 5.5,
    w: 2.5,
    h: 2.5,
    fill: { color: THEME.primary, transparency: 80 },
    line: { color: THEME.primary, transparency: 80 },
  });

  slide.addText(title, {
    x: 0.7,
    y: 2.0,
    w: 11.9,
    h: 1.3,
    fontSize: 36,
    bold: true,
    color: THEME.white,
    fontFace: FONT,
    align: "center",
  });

  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.7,
      y: 3.4,
      w: 11.9,
      h: 0.5,
      fontSize: 16,
      color: THEME.dim,
      fontFace: FONT,
      align: "center",
    });
  }

  slide.addText("Generated by AI Secretary", {
    x: 0.7,
    y: 6.7,
    w: 11.9,
    h: 0.25,
    fontSize: 10,
    color: "475569",
    fontFace: FONT,
    align: "center",
  });
}

function slideNumberBadge(ppt: Presentation, slide: Slide, index: number) {
  slide.addShape(ppt.ShapeType.ellipse, {
    x: 12.5,
    y: 0.15,
    w: 0.45,
    h: 0.45,
    fill: { color: THEME.primary },
    line: { color: THEME.primary },
  });

  slide.addText(String(index), {
    x: 12.5,
    y: 0.15,
    w: 0.45,
    h: 0.45,
    fontSize: 10,
    bold: true,
    color: THEME.white,
    fontFace: FONT,
    align: "center",
    valign: "middle",
  });
}

function addBullets(
  ppt: Presentation,
  index: number,
  title: string,
  items: string[],
) {
  const slide = ppt.addSlide();
  slide.background = { color: THEME.white };

  slideNumberBadge(ppt, slide, index);

  slide.addText(title, {
    x: 0.6,
    y: 0.25,
    w: 11.6,
    h: 0.65,
    fontSize: 28,
    bold: true,
    color: THEME.primary,
    fontFace: FONT,
  });

  slide.addShape(ppt.ShapeType.line, {
    x: 0.6,
    y: 0.95,
    w: 11.8,
    h: 0,
    line: { color: THEME.pale, width: 1.5 },
  });

  const cardHeight = 0.72;
  const gap = 0.12;

  // Six cards is what fits before the layout starts overflowing the slide.
  items.slice(0, 6).forEach((text, position) => {
    const y = 1.15 + position * (cardHeight + gap);

    slide.addShape(ppt.ShapeType.roundRect, {
      x: 0.6,
      y,
      w: 11.8,
      h: cardHeight,
      fill: { color: position % 2 === 0 ? THEME.card : THEME.offWhite },
      line: { color: THEME.cardLine },
      rectRadius: 0.08,
    });

    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.85,
      y: y + 0.25,
      w: 0.22,
      h: 0.22,
      fill: { color: THEME.primary },
      line: { color: THEME.primary },
    });

    slide.addText(text, {
      x: 1.2,
      y: y + 0.08,
      w: 10.9,
      h: cardHeight - 0.16,
      fontSize: 14,
      color: THEME.text,
      fontFace: FONT,
      valign: "middle",
    });
  });
}

function addStats(
  ppt: Presentation,
  index: number,
  title: string,
  stats: Array<{ label: string; value: string }>,
) {
  const slide = ppt.addSlide();
  slide.background = { color: THEME.dark };

  slideNumberBadge(ppt, slide, index);

  slide.addText(title, {
    x: 0.6,
    y: 0.3,
    w: 11.6,
    h: 0.65,
    fontSize: 28,
    bold: true,
    color: THEME.white,
    fontFace: FONT,
  });

  slide.addShape(ppt.ShapeType.line, {
    x: 0.6,
    y: 1.0,
    w: 11.8,
    h: 0,
    line: { color: THEME.primary, width: 2 },
  });

  const shown = stats.slice(0, 4);
  const columnWidth = 11.8 / Math.max(shown.length, 1);

  shown.forEach((stat, position) => {
    const x = 0.6 + position * columnWidth;

    slide.addShape(ppt.ShapeType.roundRect, {
      x: x + 0.1,
      y: 1.5,
      w: columnWidth - 0.2,
      h: 3.8,
      fill: { color: THEME.panel },
      line: { color: THEME.primary, width: 1 },
      rectRadius: 0.12,
    });

    slide.addText(stat.value, {
      x: x + 0.1,
      y: 1.9,
      w: columnWidth - 0.2,
      h: 1.5,
      fontSize: 40,
      bold: true,
      color: THEME.primary,
      fontFace: FONT,
      align: "center",
    });

    slide.addText(stat.label, {
      x: x + 0.1,
      y: 3.5,
      w: columnWidth - 0.2,
      h: 1.4,
      fontSize: 14,
      color: THEME.pale,
      fontFace: FONT,
      align: "center",
    });
  });
}

function addConclusion(ppt: Presentation, title: string, items: string[]) {
  const slide = ppt.addSlide();
  slide.background = { color: THEME.primary };

  slide.addShape(ppt.ShapeType.ellipse, {
    x: 10,
    y: 4.5,
    w: 5,
    h: 5,
    fill: { color: THEME.primaryDeep, transparency: 60 },
    line: { color: THEME.primaryDeep, transparency: 60 },
  });

  slide.addText(title, {
    x: 0.7,
    y: 1.0,
    w: 9,
    h: 0.9,
    fontSize: 34,
    bold: true,
    color: THEME.white,
    fontFace: FONT,
  });

  slide.addText("Key takeaways", {
    x: 0.7,
    y: 2.1,
    w: 9,
    h: 0.4,
    fontSize: 14,
    color: "BFDBFE",
    fontFace: FONT,
  });

  items.slice(0, 4).forEach((text, position) => {
    const y = 2.7 + position * 0.75;

    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.7,
      y,
      w: 0.3,
      h: 0.3,
      fill: { color: THEME.white },
      line: { color: THEME.white },
    });

    slide.addText(text, {
      x: 1.2,
      y: y - 0.05,
      w: 8.5,
      h: 0.55,
      fontSize: 15,
      color: THEME.white,
      fontFace: FONT,
    });
  });

  slide.addText("Generated by AI Secretary", {
    x: 0.7,
    y: 7.0,
    w: 11.9,
    h: 0.2,
    fontSize: 9,
    color: "BFDBFE",
    fontFace: FONT,
    align: "center",
  });
}

export async function renderDeck(spec: DeckSpec): Promise<Buffer> {
  const ppt = new Pptx();
  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "AI Secretary";
  ppt.title = spec.title;

  addCover(ppt, spec.title, spec.subtitle);

  spec.slides.forEach((slide, index) => {
    const number = index + 1;

    if (slide.type === "stats") addStats(ppt, number, slide.title, slide.stats);
    else if (slide.type === "conclusion")
      addConclusion(ppt, slide.title, slide.items);
    else addBullets(ppt, number, slide.title, slide.items);
  });

  // pptxgenjs types the return of write() loosely; nodebuffer gives a Buffer.
  return (await ppt.write({ outputType: "nodebuffer" })) as Buffer;
}
